1번 내코드


CREATE TABLE BRANDS(
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE PRODUCTS(
    PRODUCT_NO NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    PRODUCT_PRICE NUMBER NOT NULL,
    BRAND_CODE NUMBER REFERENCES BRANDS,
    SERIAL_NO VARCHAR2(100),
    SOLD_OUT CHAR(1) DEFAULT 'N' CHECK(SOLD_OUT IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_BRAND_ID
START WITH 100
INCREMENT BY 100
MAXVALUE 500
NOCYCLE;

-- SEQ_BRAND_ID : 100부터 시작해서 100씩 증가
CREATE SEQUENCE SEQ_PRODUCT_NO
START WITH 1
INCREMENT BY 1
MAXVALUE 10000
NOCYCLE;

--추가
ALTER SEQUENCE seq_brand_id MAXVALUE 1000;
SELECT * FROM user_sequences WHERE sequence_name = 'SEQ_BRAND_NAME';

INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '삼성');
INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '애플'); --NEXTVAL로 해주면 애플 들어감

INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S8', 800000, 100, 'S8','Y');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S9', 900000, 100, 'S9','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S10', 1000000, 100, 'S10','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰9S', 900000, 200, '9S','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰10S', 1000000, 200, '10S','N');

SELECT PRODUCT_NAME, PRODUCT_PRICE, BRAND_NAME, SOLD_OUT
FROM PRODUCTS JOIN BRANDS ON (BRAND_ID = BRAND_CODE);

SELECT * FROM PRODUCTS;
SELECT * FROM PRODUCTS;


1번 강사님 코드


-- BRANDS 테이블 생성
CREATE TABLE BRANDS(
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR2(100) NOT NULL
);

-- PRODUCTS 테이블 생성
CREATE TABLE PRODUCTS(
    PRODUCT_NO NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    PRODUCT_PRICE NUMBER NOT NULL,
    BRAND_CODE NUMBER REFERENCES BRANDS,
    SERIAL_NO VARCHAR2(100),
    SOLD_OUT CHAR(1) DEFAULT 'N' CHECK(SOLD_OUT IN ('Y', 'N'))
);

-- SEQ_BRAND_ID : 100부터 시작하여 100씩 증가, 최대값 1000, 반복 없음.
-- SEQ_BRAND_ID 시퀀스 생성
CREATE SEQUENCE SEQ_BRAND_ID 
START WITH 100
INCREMENT BY 100
MAXVALUE 500
NOCYCLE;
-- 조치내용
ALTER SEQUENCE seq_brand_id MAXVALUE 1000;
SELECT * FROM user_sequences WHERE sequence_name = 'SEQ_BRAND_ID';

-- SEQ_PRODUCT_NO : 1부터 시작하여 1씩 증가, 최대값 10000, 반복 없음.
-- SEQ_PRODUCT_NO 시퀀스 생성
CREATE SEQUENCE SEQ_PRODUCT_NO
START WITH 1
INCREMENT BY 1
MAXVALUE 10000
NOCYCLE;

-- brands 테이블에 데이터 넣기
INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '삼성');
INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '애플');
SELECT * FROM brands;

-- products 테이블에 데이터 
-- products 테이블에 데이터 넣기
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S8', 800000, 100, 'S8','Y');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S9', 900000, 100, 'S9','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S10', 1000000, 100, 'S10','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰9S', 900000, 200, '9S','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰10S', 1000000, 200, '10S','N');
SELECT * FROM products;

ALTER TABLE 테이블이름 ADD UNIQUE (컬럼);
ALTER TABLE products ADD UNIQUE(serial_no);


-- 재훈이형 코드 --------------------------------------------
---------------------------------------첫번째 ------------------------------------------
--BRANDS 테이블 생성
CREATE TABLE BRANDS(
BRAND_ID NUMBER PRIMARY KEY,
BRAND_NAME VARCHAR2(100) NOT NULL
);
--PRODUCTS 테이블 생성
CREATE TABLE PRODUCTS(
PRODUCT_NO NUMBER PRIMARY KEY,
PRODUCT_NAME VARCHAR2(50) NOT NULL,
PRODUCT_PRICE NUMBER NOT NULL,
BRAND_CODE NUMBER REFERENCES BRANDS,
SERIAL_NO VARCHAR2(100),
SOLD_OUT CHAR(1) DEFAULT 'N' CHECK(SOLD_OUT IN ('Y', 'N'))
);
--SEQ_BRAND_ID 시퀀스 생성
--SEQ_BRAND_ID : 100부터 시작하여 100씩 증가, 최대값 1000, 반복 없음.
--SEQ_PRODUCT_NO : 1부터 시작하여 1씩 증가, 최대값 10000, 반복 없음.
CREATE SEQUENCE SEQ_BRAND_ID
START WITH 100
INCREMENT BY 100
MAXVALUE 500
NOCYCLE;
--<변경>
ALTER SEQUENCE seq_brand_id MAXVALUE 1000;

--SEQ_PRODUCT_NO 시퀀스 생성
CREATE SEQUENCE SEQ_PRODUCT_NO
START WITH 1
INCREMENT BY 1
MAXVALUE 10000
NOCYCLE;

--BRANDS 테이블 데이터 삽입
INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '삼성');
INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '애플');
--INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '애플');  변경


--PRODUCTS 테이블 데이터 삽입
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S8', 800000, 100, 'S8','Y');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S9', 900000, 100, 'S9','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S10', 1000000, 100, 'S10','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰9S', 900000, 200, '9S','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰10S', 1000000, 200, '10S','N');
SELECT * FROM products;


--결과 조회
SELECT PRODUCT_NAME, PRODUCT_PRICE, BRAND_NAME, SOLD_OUT
FROM PRODUCTS JOIN BRANDS ON (BRAND_ID = BRAND_CODE);


ALTER  TABLE products ADD UNIQUE(serial_no);
--1. 원인 : product 테이블에 UNIQUE(serial_no)를 요구하고 있으나, 걸려있지 않음
--1. 조치내용 : ALTER  TABLE products ADD UNIQUE(serial_no);

--2. 원인 : SEQ_BRAND_ID 시퀀스가 'MAXVALUE 1000'으로 기술되어 있었지만, 생성 시 500으로 생성하고 있었음
--2. 조치내용 : ALTER SEQUENCE seq_brand_id MAXVALUE 1000;
--확인 : SELECT * FROM USER_

--1. 원인 : 애플을 INSERT하는 부분에서 NEXTVAL이 아닌 CURRVAL가 작성되어 있었음
--1. 조치내용 : 시퀀스 CURRAVAL - > NEXTVAL로 변경

--원인 키워드: UNIQUE, NEXTVAL, CURRVAL, MAXVALUE
--조치내용 키워드 : ALTER, MAXVALUE, CURRVAL, NEXTVAL
--------------------------------------------------------------

2번


-- 테이블 삭제!
DROP TABLE BRANDS CASCADE CONSTRAINTS;   
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BRAND_ID;
DROP SEQUENCE SEQ_PRODUCT_NO;
-- BRANDS 테이블 생성

CREATE TABLE BRANDS(
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR2(100) NOT NULL
);

-- PRODUCTS 테이블 생성
CREATE TABLE PRODUCTS(
    PRODUCT_NO NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    PRODUCT_PRICE NUMBER NOT NULL,
    BRAND_CODE NUMBER REFERENCES BRANDS,
    SERIAL_NO VARCHAR2(100) UNIQUE,
    SOLD_OUT CHAR(1) DEFAULT 'N' CHECK(SOLD_OUT IN ('Y', 'N'))
);

-- SEQ_BRAND_ID : 100부터 시작하여 100씩 증가, 최대값 1000, 반복 없음.
-- SEQ_BRAND_ID 시퀀스 생성
CREATE SEQUENCE SEQ_BRAND_ID 
START WITH 100
INCREMENT BY 100
MAXVALUE 500
NOCYCLE;
-- 조치내용
ALTER SEQUENCE seq_brand_id MAXVALUE 1000;
SELECT * FROM user_sequences WHERE sequence_name = 'SEQ_BRAND_ID';

-- SEQ_PRODUCT_NO : 1부터 시작하여 1씩 증가, 최대값 10000, 반복 없음.
-- SEQ_PRODUCT_NO 시퀀스 생성
CREATE SEQUENCE SEQ_PRODUCT_NO
START WITH 100
INCREMENT BY 100
MAXVALUE 10000
NOCYCLE;

-- brands 테이블에 데이터 넣기
INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '삼성');
INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '애플');
SELECT * FROM brands;

-- products 테이블에 데이터 
-- products 테이블에 데이터 넣기
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S8', 800000, 100, 'S8','Y');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S9', 900000, 100, 'S9','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S10', 1000000, 100, 'S10','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰9S', 900000, 200, '9S','N');
--유니크 제약조건이 걸려있음
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰10S', 1000000, 200, '10S','N'); 
SELECT * FROM products;

ALTER TABLE 테이블이름 ADD UNIQUE (컬럼);
ALTER TABLE products ADD UNIQUE(serial_no);

-- 1. 조치
ALTER TABLE products MODIFY (sold_out DEFAULT 'N');
SELECT *FROM products;
UPDATE products SET sold_out = 'N' WHERE sold_out IS NULL;

--2. 조치
ALTER SEQUENCE SEQ_PRODUCT_NO INCREMENT BY 1;

-- 3. 조치
SELECT * FROM products;
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰10S', 1000000, 200, '10s',DEFAULT);

3번 